// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | PhotoIndexSlice
  | GalleryHeroSlice
  | ProductDetailSlice
  | ContactFormSectionSlice
  | ProductIndexSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice = ProductDetailSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Price Range field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price_range
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price_range: prismic.KeyTextField;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

export type AllDocumentTypes = PageDocument | ProductDocument;

/**
 * Primary content in *ContactFormSection → Primary*
 */
export interface ContactFormSectionSliceDefaultPrimary {
  /**
   * Heading field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for ContactFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSection*
 */
type ContactFormSectionSliceVariation = ContactFormSectionSliceDefault;

/**
 * ContactFormSection Shared Slice
 *
 * - **API ID**: `contact_form_section`
 * - **Description**: ContactFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSlice = prismic.SharedSlice<
  "contact_form_section",
  ContactFormSectionSliceVariation
>;

/**
 * Primary content in *GalleryHero → Primary*
 */
export interface GalleryHeroSliceDefaultPrimary {
  /**
   * Heading field in *GalleryHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *GalleryHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for GalleryHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryHero*
 */
type GalleryHeroSliceVariation = GalleryHeroSliceDefault;

/**
 * GalleryHero Shared Slice
 *
 * - **API ID**: `gallery_hero`
 * - **Description**: GalleryHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryHeroSlice = prismic.SharedSlice<
  "gallery_hero",
  GalleryHeroSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *PhotoIndex → Items*
 */
export interface PhotoIndexSliceDefaultItem {
  /**
   * GalleryImage field in *PhotoIndex → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photo_index.items[].galleryimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  galleryimage: prismic.ImageField<never>;
}

/**
 * Default variation for PhotoIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<PhotoIndexSliceDefaultItem>
>;

/**
 * Slice variation for *PhotoIndex*
 */
type PhotoIndexSliceVariation = PhotoIndexSliceDefault;

/**
 * PhotoIndex Shared Slice
 *
 * - **API ID**: `photo_index`
 * - **Description**: PhotoIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotoIndexSlice = prismic.SharedSlice<
  "photo_index",
  PhotoIndexSliceVariation
>;

/**
 * Default variation for ProductDetail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDetailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProductDetail*
 */
type ProductDetailSliceVariation = ProductDetailSliceDefault;

/**
 * ProductDetail Shared Slice
 *
 * - **API ID**: `product_detail`
 * - **Description**: ProductDetail
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDetailSlice = prismic.SharedSlice<
  "product_detail",
  ProductDetailSliceVariation
>;

/**
 * Default variation for ProductIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProductIndex*
 */
type ProductIndexSliceVariation = ProductIndexSliceDefault;

/**
 * ProductIndex Shared Slice
 *
 * - **API ID**: `product_index`
 * - **Description**: ProductIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductIndexSlice = prismic.SharedSlice<
  "product_index",
  ProductIndexSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactFormSectionSlice,
      ContactFormSectionSliceDefaultPrimary,
      ContactFormSectionSliceVariation,
      ContactFormSectionSliceDefault,
      GalleryHeroSlice,
      GalleryHeroSliceDefaultPrimary,
      GalleryHeroSliceVariation,
      GalleryHeroSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PhotoIndexSlice,
      PhotoIndexSliceDefaultItem,
      PhotoIndexSliceVariation,
      PhotoIndexSliceDefault,
      ProductDetailSlice,
      ProductDetailSliceVariation,
      ProductDetailSliceDefault,
      ProductIndexSlice,
      ProductIndexSliceVariation,
      ProductIndexSliceDefault,
    };
  }
}
