// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  gallery_hero: dynamic(() => import("./GalleryHero")),
  hero: dynamic(() => import("./Hero")),
  photo_index: dynamic(() => import("./PhotoIndex")),
  product_detail: dynamic(() => import("./ProductDetail")),
  product_index: dynamic(() => import("./ProductIndex")),
};
